// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgn18Dzy9-hdWpB3VkMjn7DhhEBdFRQpY',
    appId: '1:581923709768:web:ed5e332b23b1b5ab24097d',
    messagingSenderId: '581923709768',
    projectId: 'e-commerce-12041',
    authDomain: 'e-commerce-12041.firebaseapp.com',
    storageBucket: 'e-commerce-12041.firebasestorage.app',
    measurementId: 'G-X0KCHM8XM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLc8Xm3nV3FjxtWLFKU-BxynSz3tjuu5I',
    appId: '1:581923709768:android:8e71bdfaaafd294824097d',
    messagingSenderId: '581923709768',
    projectId: 'e-commerce-12041',
    storageBucket: 'e-commerce-12041.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxMvcH5WKgUO7EySvZYQ8uHdOCM_BR2Q',
    appId: '1:581923709768:ios:9bbb4bcd2d84d03224097d',
    messagingSenderId: '581923709768',
    projectId: 'e-commerce-12041',
    storageBucket: 'e-commerce-12041.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceProject',
  );
}
